apiVersion: v1
kind: Service
metadata:
  name: demoappsvc
spec:
  # If you can't use LoadBalancer, use NodePort instead
  # type: NodePort
  type: LoadBalancer
  # Select the pod with the same label
  selector:
    app: demoapp
  # route the traffic from service port 80 to container port 8080
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
